[package]
name = "dreamfield_system"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
gl = "0.14.0"
glfw = "0.45.0"
bevy_ecs = "0.8.1"
gltf = { version = "1.0", features = ["extras", "names"] }
cgmath = "0.18.0"
byteorder = "1.4.3"
speedy = "0.8.3"
include_dir = "0.7.2"
