[package]
name = "dreamfield_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.98"
quote = "1.0.20"
std140 = "0.2.5"
dreamfield_traits = { path = "../dreamfield_traits" }
